  - name: Waiting for nextcloud setup (5 min max)...
    wait_for:
      path: ~/nextcloud/nextcloud/config/config.php
    when: '"nextcloud" in services'

  - name: set apache to force http redirect (fixes some client connections behind proxies)
    lineinfile:
      path: /home/{{ username }}/nextcloud/nextcloud/config/config.php
      regexp: "^  'overwriteprotocol'"
      line: "  'overwriteprotocol' => 'https',"
      insertbefore: "  'htaccess.RewriteBase'"
    become: yes
    register: https_redirection
    when: '"nextcloud" in services'

  - name: restart nextcloud
    docker_compose:
      project_src: ~/nextcloud
      build: yes
      restarted: yes
    when: '"nextcloud" in services and  https_redirection.changed'